name: Vale Linter
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Vale
        uses: errata-ai/vale-action@v2.0.0
        with:
        
          files: vale-tutorial
          # Optional
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip

        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
